/******** Manually ASSIGN TRAINER TO DEMO STUDY in physician_tracking **********/
INSERT INTO `epic_prod`.`study_site` (`study_id`, `site_id`) VALUES (2271, 114);
INSERT INTO `epic_prod`.`study_site` (`study_id`, `site_id`) VALUES (2272, 114);
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '2271', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '2272', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '91950', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '91986', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '91951', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92085', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92136', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92141', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '921601', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '921602', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92162', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92163', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92190', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92201', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92219', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92217', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92218', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92191', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92221', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92226', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92241', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92250', '114', 'yes', 'ACTIVE');
INSERT INTO `epic_prod`.`physician_tracking` (`physician_id`, `study_id`, `site_id`, `willing`, `screening_status`) VALUES ('1098', '92255', '114', 'yes', 'ACTIVE');
